config/routes.rb
Opintorekisteri::Application.routes.draw do
  resources :courses

  resources :paths

  resources :groups do
    match :path, :via => [:get], :on => :member
    match :touch, :via => [:get], :on => :collection
  end

  resources :posts

  resources :statistics do
    match :touch, :via => [:post], :on => :member
    match :show_month_after, :via => [:get], :on => :member
  end

  resources :students

  resources :entries

  root :to => 'groups#index'

  match 'api/student/:id'              => 'api#student'
  match 'api/groups'                   => 'api#groups'
  match 'api/groups/:id'               => 'api#group'
  match 'api/groups/:id/:year/:sorted' => 'api#group_year'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :code, :creditDate, :credits, :date, :grade, :name, :ordering, :status, :statuscode, :student_number

  belongs_to :student

  def self.unknown? entry
    Entry.where( :student_number => entry.student_number,
                 :date => entry.date,
                 :name => entry.name,
                 :grade => entry.grade).empty?
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    dd = @entry.creditDate.split(".")[0].to_i
    mm = @entry.creditDate.split(".")[1].to_i
    yy = @entry.creditDate.split(".")[2].to_i

    @entry.date = Date.new(yy, mm, dd)

    respond_to do |format|
      if Entry.unknown?(@entry) and @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry, status: :created, location: @entry }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :credits %><br />
    <%= f.text_field :credits %>
  </div>
  <div class="field">
    <%= f.label :grade %><br />
    <%= f.text_field :grade %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :statuscode %><br />
    <%= f.number_field :statuscode %>
  </div>
  <div class="field">
    <%= f.label :ordering %><br />
    <%= f.text_field :ordering %>
  </div>
  <div class="field">
    <%= f.label :creditDate %><br />
    <%= f.text_field :creditDate %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h2>Listing entries</h2>

<table class="table table-striped">
  <tr>
    <th>Student</th>
    <th>Code</th>
    <th>Name</th>
    <th>Credits</th>
    <th>Grade</th>
    <th>Status</th>
    <th>Statuscode</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.student_number %></td>
    <td><%= entry.code %></td>
    <td><%= entry.name %></td>
    <td><%= entry.credits %></td>
    <td><%= entry.grade %></td>
    <td><%= entry.status %></td>
    <td><%= entry.statuscode %></td>
    <td><%= entry.date %></td>
    <td><%= link_to 'Show', entry %></td>
    <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
    <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @entry.code %>
</p>

<p>
  <b>Name:</b>
  <%= @entry.name %>
</p>

<p>
  <b>Credits:</b>
  <%= @entry.credits %>
</p>

<p>
  <b>Grade:</b>
  <%= @entry.grade %>
</p>

<p>
  <b>Status:</b>
  <%= @entry.status %>
</p>

<p>
  <b>Statuscode:</b>
  <%= @entry.statuscode %>
</p>

<p>
  <b>Ordering:</b>
  <%= @entry.ordering %>
</p>

<p>
  <b>Creditdate:</b>
  <%= @entry.creditDate %>
</p>

<p>
  <b>Date:</b>
  <%= @entry.date %>
</p>


<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>