config/routes.rb
Opintorekisteri::Application.routes.draw do
  resources :courses

  resources :paths

  resources :groups do
    match :path, :via => [:get], :on => :member
    match :touch, :via => [:get], :on => :collection
  end

  resources :posts

  resources :statistics do
    match :touch, :via => [:post], :on => :member
    match :show_month_after, :via => [:get], :on => :member
  end

  resources :students

  resources :entries

  root :to => 'groups#index'

  match 'api/student/:id'              => 'api#student'
  match 'api/groups'                   => 'api#groups'
  match 'api/groups/:id'               => 'api#group'
  match 'api/groups/:id/:year/:sorted' => 'api#group_year'

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :attrib, :started, :student_number, :month_credits

  serialize :month_credits

  has_many :entries
  has_many :memberships
  has_many :groups, :through => :memberships

  default_scope includes(:entries)

  def self.belonging_to started, attrib, attrib2
    return Student.includes(:entries).where("started == ? and attrib LIKE ?", started, "%#{attrib}%") if attrib2.nil? or attrib2.empty?
    #Student.includes(:entries).where("started == ? and attrib == ? and attrib2 == ?", started, attrib, attrib2)
    Student.includes(:entries).where("started == ? and attrib LIKE ? and attrib2 LIKE ?", started, "%#{attrib}%", "%#{attrib2}%")
  end

  def months_studied
    start_year = started[1..-1].to_i
    date1 = Date.new(start_year, 8, 1)
    (((Date.today+1.month - date1)/30).to_i)
  end

  def progress
    (1..months_studied).inject([]) do |progr, m|
      progr << credits_in_months(m).to_i
    end
  end

  def progress_since date, months
    (1..months).inject([]) do |progr, m|
      progr << credits_in_months_starting(m,date).to_i
    end
  end

  def member_of group
    groups.include? group
  end

  def has_completed course
    entries.each do |e|
      return true if not e.name.nil? and e.name.include? course and e.statuscode != 10
    end
    false
  end

  # reason for useless parameter is to keep interface similar to other methods
  def credits_total year = 0
    success.inject(0) do |sum, e|
      sum += e.credits if likely_a_course e
      sum
    end
  end

  def tkt_credits
    success.inject(0) do |sum, e|
      sum += e.credits if likely_a_course e and e.code.start_with?('58')
      sum
    end
  end

  def credits_after
    date1 = Date.new(2012, 8, 1)
    date2 = Date.new(2013, 8, 1)
    success_at_period(date1, date2).inject(0) do |sum, e|
      sum += e.credits if likely_a_course e
      sum
    end
  end

  def average_grade
    credits = 0
    number_sum = 0
    entries.each do |e|
      if likely_a_course(e) and (e.grade.to_i) > 0
        number_sum += e.grade.to_i * e.credits
        credits += e.credits
      end
    end
    return 0 if credits == 0
    number_sum / credits
  end

  # year

  def credits_registered_year year, dep = nil
    date1 = Date.new(year, 8, 1)
    date2 = Date.new(year+1, 8, 1)
    success_at_period(date1, date2).inject(0) do |sum, e|
      sum += e.credits if (dep.nil? or e.code.starts_with? dep) and likely_a_course e
      sum
    end
  end

  def tkt_credits_completed_year year
    credits_completed_year(year, "58")
  end

  def math_credits_completed_year year
    credits_completed_year(year, "57")
  end

  def credits_completed_year year, dep = nil
    date1 = Date.new(year, 8, 1)
    date2 = Date.new(year+1, 8, 1)
    completed_at_period(date1, date2).inject(0) do |sum, e|
      sum += e.credits if (dep.nil? or e.code.starts_with? dep) and likely_a_course e
      sum
    end
  end

  def other_credits_completed_year year
    credits_completed_year(year) - credits_completed_year(year, "58") -credits_completed_year(year, "57")
  end

  # hack_begin

  def credits_in_months month
    if not month_credits.nil? and month_credits[month]
      return month_credits[month]
    end

    start_year = started[1..-1].to_i
    date1 = Date.new(start_year, 8, 1)
    date2 = date1 + month.month
    cred = success_at_period(date1, date2).inject(0) do |sum, e|
      sum += e.credits if likely_a_course e
      sum
    end

    if self.month_credits.nil?
      self.month_credits = {}
    end

    self.month_credits[month] = cred
    self.save
    cred
  end

  def credits_in_months_starting month, starting
    upto = starting + month.month

    cred = success_at_period(starting, upto).inject(0) do |sum, e|
      sum += e.credits if likely_a_course e
      sum
    end
    cred
  end

  def tkt_credits_in_months_starting month, starting
    upto = starting + month.month
    cred = success_at_period(starting, upto).inject(0) do |sum, e|
      sum += e.credits if e.code.starts_with? "58" and likely_a_course e
      sum
    end
    cred
  end

  ## not needed

  def credits_completed_in_months month, dep = nil
    start_year = started[1..-1].to_i
    date1 = Date.new(start_year, 8, 1)
    date2 = date1 + month.month
    success_at_period(date1, date2).inject(0) do |sum, e|
      sum += e.credits if (dep.nil? or e.code.starts_with? dep) and likely_a_course e
      sum
    end
  end

  def other_credits_completed_in_months months
    credits_completed_in_months(months) - credits_completed_in_months(months, "58") -credits_completed_in_months(months, "57")
  end

  # not needed_end

  def success
    entries.where("statuscode != ? ", 10)
  end

  def failed
    entries.where(:statuscode => 10)
  end

  def completed_at_period date1, date2
    entries.where("statuscode == ? and date >= ? and date < ?", 4, date1, date2)
  end

  # sisältää hyväksiluetut
  def success_at_period date1, date2
    entries.where("statuscode != ? and date >= ? and date < ?", 10, date1, date2)
  end

  def not_a_course e
    e.code.start_with?('0') or e.credits > 15
  end

  def likely_a_course e
    not not_a_course(e) or (e.name.include?("gradu") and not e.name.include?("ilman"))
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])

    i = 1
    @plot = []
    @student.progress.each do |s|
      @plot << [i, s]
      i += 1
    end
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    exists = Student.where(:student_number => @student.student_number)

    respond_to do |format|
      if exists.empty? and @student.save
        format.html { redirect_to @student, :notice => 'Student was successfully created.' }
        format.json { render :json => @student, :status => :created, :location => @student }
      else
        format.html { render :action => "new" }
        format.json { render :json => @student, :status => :created, :location => @student }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, :notice => 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_number %><br />
    <%= f.text_field :student_number %>
  </div>
  <div class="field">
    <%= f.label :started %><br />
    <%= f.text_field :started %>
  </div>
  <div class="field">
    <%= f.label :attrib %><br />
    <%= f.text_field :attrib %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h2>Listing students</h2>

<table class="table table-striped">
  <tr>
    <th>Student number</th>
    <th>Started</th>
    <th>Attribute</th>
    <th></th>
  </tr>

  <% @students.each do |student| %>
      <tr>
        <td><%= link_to student_number(student), student %></td>
        <td><%= student.started %></td>
        <td><%= student.attrib %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <!--
    <td><%= link_to 'Destroy', student, method: :delete, data: {confirm: 'Are you sure?' } %></td>
  -->
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<% content_for :head do %>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['', ''],
            <% @plot.each do |p| %>
            <%="[#{p[0]},#{p[1]}]"%>,
            <% end %>
        ]);

        var options = {
            hAxis: { title:'months'},
            vAxis: { title:'credits'},
            legend: { position:'none' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>

<% end %>

<p id="notice"><%= notice %></p>

<p>
  <b>Student number:</b>
  <%= student_number(@student) %>
</p>

<p>
  <b>Started:</b>
  <%= @student.started %>
</p>

<p>
  <b>Credits:</b>
  <%= @student.credits_total %>
</p>

<p><b>Progress</b></p>

<div id="chart_div"></div>

<p><b>Statistic groups</b></p>

<ul>
  <% @student.groups.each do |group| %>
      <li><%= link_to group.name, group_path(group, :order => "credits_completed_year", :year => 2012), :rel => 'tooltip', :title => group.description %></li>
  <% end %>
</ul>

<h2>successful</h2>

<table class="table table-striped">
  <tr>
    <th>Course</th>
    <th>Credits</th>
    <th>Grade</th>
    <th>Date</th>
    <th>Statucode</th>
    <th>Code</th>
  </tr>

  <% @student.success.sort_by { |s| s.date }.reverse.each do |entry| %>
      <tr>
        <td><%= entry.name %></td>
        <td><%= entry.credits %></td>
        <td><%= entry.grade %></td>
        <td><%= entry.date %></td>
        <td><%= entry.statuscode %></td>
        <td><%= entry.code %></td>
      </tr>
  <% end %>
</table>

<h2>failed</h2>

<table class="table table-striped">
  <tr>
    <th>Course</th>
    <th>Credits</th>
    <th>Grade</th>
    <th>Date</th>
    <th>Code</th>
  </tr>

  <% @student.failed.each do |entry| %>
      <tr>
        <td><%= entry.name %></td>
        <td><%= entry.credits %></td>
        <td><%= entry.grade %></td>
        <td><%= entry.date %></td>
        <td><%= entry.statuscode %></td>
      </tr>
  <% end %>
</table>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>