config/routes.rb
Opintorekisteri::Application.routes.draw do
  resources :courses

  resources :paths

  resources :groups do
    match :path, :via => [:get], :on => :member
    match :touch, :via => [:get], :on => :collection
  end

  resources :posts

  resources :statistics do
    match :touch, :via => [:post], :on => :member
    match :show_month_after, :via => [:get], :on => :member
  end

  resources :students

  resources :entries

  root :to => 'groups#index'

  match 'api/student/:id'              => 'api#student'
  match 'api/groups'                   => 'api#groups'
  match 'api/groups/:id'               => 'api#group'
  match 'api/groups/:id/:year/:sorted' => 'api#group_year'

end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
  attr_accessible :attrib, :attrib2, :started

  def aggregate year=2012
    Statistic.aggregate(Student.belonging_to(started, attrib, attrib2), year)
  end

  def self.aggregate students, year
    credits_year = 0
    credits_completed_year = 0
    zeros = 0
    fiftyfive = 0
    credits_tkt = 0
    credits_math = 0
    zerotkt = 0
    credits_tktactive = 0

    students.each do |s|
      credits_year += s.credits_year year
      credits_completed_year += s.credits_completed_year year
      credits_tkt += s.credits_completed_year(year, "58")
      credits_math += s.credits_completed_year(year, "57")
      fiftyfive += 1 if s.credits_year(year) > 54
      zeros += 1 if s.credits_year(year) == 0
    end

    active_students = students.count-zeros

    #if not students.nil? and ( students.first.attrib == "mooc" or ( students.first.attrib.include?"kesa" and students.last.attrib.include?"kesa" ))
    #  credits_completed_year = credits_completed_year-(9*active_students)
    #  credits_tkt = credits_tkt-(9*active_students)
    #  credits_tktactive = credits_tktactive-(9*active_students)
    #end

    {
        :year => year,
        :total => (credits_year/active_students).round(2),
        :completed => (credits_completed_year/active_students).round(2),
        :tkt => (credits_tkt/active_students).round(2),
        :math => (credits_math/active_students).round(2),
        :other => ((credits_completed_year-credits_math-credits_tkt)/active_students).round(2),
        :students => students.count,
        :fiftyfive => fiftyfive,
        :zeros => zeros,
    }
  end

  # hack

  def month_aggregate year=2012
    Statistic.month_aggregate(Student.belonging_to(started, attrib, attrib2), year)
  end

  def self.month_aggregate students, year
    credits_year = 0
    credits_completed_year = 0
    zeros = 0
    fiftyfive = 0
    credits_tkt = 0
    credits_math = 0
    zerotkt = 0
    credits_tktactive = 0

    students.each do |s|
      credits_year += s.credits_in_months year
      credits_completed_year += s.credits_completed_in_months year
      credits_tkt += s.credits_completed_in_months(year, "58")
      credits_math += s.credits_completed_in_months(year, "57")
      fiftyfive += 1 if s.credits_in_months(year) > 54
      zeros += 1 if s.credits_in_months(year) == 0
    end

    active_students = students.count-zeros

    #if not students.nil? and students.first.attrib != "norm"
    #  credits_completed_year = credits_completed_year-(9*active_students)
    #  credits_tkt = credits_tkt-(9*active_students)
    #  credits_tktactive = credits_tktactive-(9*active_students)
    #end

    {
        :year => year,
        :total => (credits_year/active_students).round(2),
        :completed => (credits_completed_year/active_students).round(2),
        :tkt => (credits_tkt/active_students).round(2),
        :math => (credits_math/active_students).round(2),
        :other => ((credits_completed_year-credits_math-credits_tkt)/active_students).round(2),
        :students => students.count,
        :fiftyfive => fiftyfive,
        :zeros => zeros,
    }
  end

  # hack end

  def already_started year
    started[1..-1].to_i <= year
  end

  def to_s
    "#{started} #{attrib} #{attrib2}"
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  caches_action :index

  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = Statistic.all.sort_by { |s| s.started }
    @keys = @statistics.first.aggregate.keys

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @statistics }
    end
  end

  def touch
    @statistic = Statistic.find(params[:id])
    @statistic.touch

    redirect_to :back
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
    @statistic = Statistic.find(params[:id])

    if stale?(:last_modified => @statistic.updated_at.utc, :etag => @statistic)

      if params[:year]
        @year = params[:year].to_i
      else
        @year = 2012
      end

      @students = Student.belonging_to(@statistic.started, @statistic.attrib, @statistic.attrib2)

      if params[:order] == "credits_total"
        m = "credits"
        @students.sort_by! { |s| s.credits_total }

        i = 1
        @plot = []
        @students.each do |s|
          @plot << [i, s.credits.to_i, s.id]
          i += 1
        end

      elsif params[:order] == "credits_registered"
        m = "credits_year"
        @students.sort_by! { |s| s.credits_registered_year(@year) }

        i = 1
        @plot = []
        @students.each do |s|
          @plot << [i, s.credits_year(@year).to_i, s.id]
          i += 1
        end

      elsif params[:order] == "tkt_credits_completed"
        @students.sort_by! { |s| s.tkt_credits_completed_year(@year) }

        i = 1
        @plot = []
        @students.each do |s|
          @plot << [i, s.tkt_credits_completed_year(@year).to_i, s.id]
          i += 1
        end

      elsif params[:order] == "math_credits_completed"
        @students.sort_by! { |s| s.math_credits_completed_year(@year).to_i }

        i = 1
        @plot = []
        @students.each do |s|
          @plot << [i, s.math_credits_completed_year(@year).to_i, s.id]
          i += 1
        end

      elsif params[:order] == "other_credits_completed"
        @students.sort_by! { |s| s.other_credits_completed_year(@year) }

        i = 1
        @plot = []
        @students.each do |s|
          @plot << [i, s.other_credits_completed_year(@year).to_i, s.id]
          i += 1
        end
      else
        #"credits_completed_year"
        @students.sort_by! { |s| s.credits_completed_year(@year) }

        i = 1
        @plot = []
        @students.each do |s|
          @plot << [i, s.credits_completed_year(@year).to_i, s.id]
          i += 1
        end
      end

      @sorted = params[:order]

      @students.reverse!
      @aggregate = Statistic.aggregate @students, @year

      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @statistic }
      end
    end
  end

  # GET /statistics/new
  # GET /statistics/new.json
  def new
    @statistic = Statistic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @statistic }
    end
  end

  # GET /statistics/1/edit
  def edit
    @statistic = Statistic.find(params[:id])
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(params[:statistic])

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, :notice => 'Statistic was successfully created.' }
        format.json { render :json => @statistic, :status => :created, :location => @statistic }
      else
        format.html { render :action => "new" }
        format.json { render :json => @statistic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /statistics/1
  # PUT /statistics/1.json
  def update
    @statistic = Statistic.find(params[:id])

    respond_to do |format|
      if @statistic.update_attributes(params[:statistic])
        format.html { redirect_to @statistic, :notice => 'Statistic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @statistic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic = Statistic.find(params[:id])
    @statistic.destroy

    respond_to do |format|
      format.html { redirect_to statistics_url }
      format.json { head :no_content }
    end
  end


  # GET /statistics/1
  # GET /statistics/1.json
  def show_month_after
    @statistic = Statistic.find(params[:id])

    if stale?(:last_modified => @statistic.updated_at.utc, :etag => @statistic)

      @year = params[:month].to_i

      @students = Student.belonging_to(@statistic.started, @statistic.attrib, @statistic.attrib2)

      if params[:order] == "credits_total"
        m = "credits"
        @students.sort_by! { |s| s.credits }

        i = 1
        @plot = []
        @students.each do |s|
          @plot << [i, s.credits.to_i]
          i += 1
        end

      elsif params[:order] == "credits_registered"
        m = "credits_year"
        @students.sort_by! { |s| s.credits_in_months(@year) }

        i = 1
        @plot = []
        @students.each do |s|
          @plot << [i, s.credits_in_months(@year).to_i]
          i += 1
        end

      elsif params[:order] == "tkt_credits_completed"
        @students.sort_by! { |s| s.credits_completed_in_months(@year, "58") }

        i = 1
        @plot = []
        @students.each do |s|
          @plot << [i, s.credits_completed_in_months(@year, "58").to_i]
          i += 1
        end

      elsif params[:order] == "math_credits_completed"
        @students.sort_by! { |s| s.credits_completed_in_months(@year, "57").to_i }

        i = 1
        @plot = []
        @students.each do |s|
          @plot << [i, s.credits_completed_in_months(@year, "57").to_i]
          i += 1
        end

      elsif params[:order] == "other_credits_completed"
        @students.sort_by! { |s| s.other_credits_completed_in_months(@year).to_i }

        i = 1
        @plot = []
        @students.each do |s|
          @plot << [i, s.other_credits_completed_in_months(@year).to_i]
          i += 1
        end
      else
        @students.sort_by! { |s| s.credits_completed_in_months(@year).to_i }

        i = 1
        @plot = []
        @students.each do |s|
          @plot << [i, s.credits_completed_in_months(@year).to_i]
          i += 1
        end
      end

      @sorted = params[:order] || "credits_completed_year"

      @students.reverse!
      @aggregate = Statistic.month_aggregate @students, @year

      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @statistic }
      end
    end
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/_form.html.erb
<%= form_for(@statistic) do |f| %>
  <% if @statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statistic.errors.count, "error") %> prohibited this statistic from being saved:</h2>

      <ul>
      <% @statistic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :started %><br />
    <%= f.text_field :started %>
  </div>
  <div class="field">
    <%= f.label :attrib %><br />
    <%= f.text_field :attrib %>
  </div>
    <div class="field">
      <%= f.label :attrib2 %><br />
      <%= f.text_field :attrib2 %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statistics/edit.html.erb
<h1>Editing statistic</h1>

<%= render 'form' %>

<%= link_to 'Show', @statistic %> |
<%= link_to 'Back', statistics_path %>

app/views/statistics/index.html.erb
<h2>Statistics</h2>

<table class="table table-striped">
  <tr>
    <th></th>
    <% @keys.each do |key| %>
        <th><%= key %></th>
    <% end %>
  </tr>

  <% [2012, 2011, 2010].each do |year| %>
      <% @statistics.each do |statistic| %>
          <% if statistic.already_started(year) %>
              <tr align="center">
                <td><%= link_to statistic, statistic_path(statistic, :order => "credits_completed", :year => year) %></td>
                <% @keys.each do |key| %>
                    <td><%= statistic.aggregate(year)[key] %></td>
                <% end %>
              </tr>
          <% end %>
      <% end %>
  <% end %>

</table>

<br/>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_statistic_path,
            :class => 'btn btn-primary' %>

app/views/statistics/new.html.erb
<h1>New statistic</h1>

<%= render 'form' %>

<%= link_to 'Back', statistics_path %>

app/views/statistics/show.html.erb
<% content_for :head do %>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load("visualization", "1", {packages:["corechart"]});
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['', 'Credits'],
                <% @plot.each do |p| %>
                <%="[#{p[0]},#{p[1]}]"%>,
                <% end %>
            ]);

            var map = {
                <% @plot.each do |p| %>
                   <%="#{p[0]}:#{p[2]}"%>,
                   <% end %>
             };

            var options = {
                title:'<%=@sorted%>',
                hAxis:{title:'', minValue:0, maxValue: <%= @plot.size %>},
                vAxis:{title:'', minValue:0, maxValue: <%= 130 %> },
                height:400,
                pointSize: 3,
                legend:'none'
            };

            var chart = new google.visualization.ScatterChart(document.getElementById('chart_div'));

            function selectHandler() {
              var selectedItem = chart.getSelection()[0];
              if (selectedItem) {
                var i = data.getValue(selectedItem.row, 0);
                open("http://rage.jamo.fi/students/"+map[i],'_self');
              }
            }

            google.visualization.events.addListener(chart, 'select', selectHandler);

            chart.draw(data, options);
        }

    </script>

<% end %>

<h2><%= @statistic %> year: <%=@year %>-<%=@year-1999 %> </h2>

<div class="container">
  <div class="row">
    <div class="span2">
      <h3>Statistics</h3>
      <table>
        <% @aggregate.keys.each do |key| %>
            <tr>
              <td> <%= key %> </td>
              <td> <%= @aggregate[key] %> </td>
            </tr>
        <% end %>
      </table>
    </div>
    <div class="span10">
      <div id="chart_div"></div>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <h2>Students sorted by <%= @sorted %> </h2>

      <p><em>sort by clicking a colum header</em></p>

      <table >
        <tr>
          <th></th>
          <th>Student number</th>
          <th> <%= link_to "credits total", statistic_path(@statistic, :year => @year, :order => "credits_total") %> </th>
          <th> <%= link_to "credits registered", statistic_path(@statistic,:year => @year,  :order => "credits_registered") %> </th>
          <th> <%= link_to "credits completed", statistic_path(@statistic, :year => @year,  :order => "credits_completed") %> </th>
          <th> <%= link_to "tkt completed", statistic_path(@statistic, :year => @year, :order => "tkt_credits_completed") %> </th>
          <th> <%= link_to "math completed", statistic_path(@statistic, :year => @year, :order => "math_credits_completed") %> </th>
          <th> <%= link_to "other completed", statistic_path(@statistic, :year => @year, :order => "other_credits_completed") %> </th>
        </tr>

        <% i=0 %>
        <% @students.each do |student| %>
            <tr>
              <td><%= i+=1; i %></td>
              <td><%= link_to student_number(student), student %></td>
              <td><%= student.credits %></td>
              <td><%= student.credits_year @year %></td>
              <td><%= student.credits_completed_year @year %></td>
              <td><%= student.credits_completed_year @year, "58" %></td>
              <td><%= student.credits_completed_year @year, "57" %></td>
              <td><%= student.other_credits_completed_year @year %></td>
            </tr>
        <% end %>
      </table>

      <!--
      If new data is entered to database you might need to
      <%= button_to( "reset the broser cache", touch_statistic_path(@statistic)  ) %>
      -->
    </div>
  </div>
</div>

app/views/statistics/show_month_after.html.erb
<% content_for :head do %>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load("visualization", "1", {packages:["corechart"]});
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['', 'Credits'],
                <% @plot.each do |p| %>
                <%= p %>,
                <% end %>
            ]);

            var options = {
                title:'<%=@sorted%>',
                hAxis:{title:'', minValue:0, maxValue: <%= @plot.size %>},
                vAxis:{title:'', minValue:0, maxValue: <%= @plot.last.last %> },
                legend:'none'
            };

            var chart = new google.visualization.ScatterChart(document.getElementById('chart_div'));
            chart.draw(data, options);
        }

    </script>

<% end %>

<h2><%= @statistic %></h2>

<h3>statistics for <%=@year %> monts after start of studies</h3>

<div class="container">
  <div class="row">
    <div class="span2">
      <h3>Statistics</h3>
      <table>
        <% @aggregate.keys.select{ |k| k!="year"}.each do |key| %>
            <tr>
              <td> <%= key  %> </td>
              <td> <%= @aggregate[key] %> </td>
            </tr>
        <% end %>
      </table>
    </div>
    <div class="span10">
      <div id="chart_div" style="height: 300px;"></div>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <h2>Sorted by <%= @sorted %> </h2>

      <p><em>sort by clicking a colum header</em></p>

      <table >
        <tr>
          <th></th>
          <th>Student number</th>
          <th> <%= link_to "credits total", show_month_after_statistic_path(@statistic, :year => @year, :order => "credits_total") %> </th>
          <th> <%= link_to "credits registered", show_month_after_statistic_path(@statistic,:year => @year,  :order => "credits_registered") %> </th>
          <th> <%= link_to "credits completed", show_month_after_statistic_path(@statistic, :year => @year,  :order => "credits_completed") %> </th>
          <th> <%= link_to "tkt completed", show_month_after_statistic_path(@statistic, :year => @year, :order => "tkt_credits_completed") %> </th>
          <th> <%= link_to "math completed", show_month_after_statistic_path(@statistic, :year => @year, :order => "math_credits_completed") %> </th>
          <th> <%= link_to "other completed", show_month_after_statistic_path(@statistic, :year => @year, :order => "other_credits_completed") %> </th>
        </tr>

        <% i=0 %>
        <% @students.each do |student| %>
            <tr>
              <td><%= i+=1; i %></td>
              <!--
              <td><%= link_to student.student_number, student %></td>
              -->
              <td><%= link_to "Na", student %></td>
              <td><%= student.credits %></td>
              <td><%= student.credits_in_months @year %></td>
              <td><%= student.credits_completed_in_months @year %></td>
              <td><%= student.credits_completed_in_months @year, "58" %></td>
              <td><%= student.credits_completed_in_months @year, "57" %></td>
              <td><%= student.other_credits_completed_in_months @year %></td>
            </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>