config/routes.rb
Opintorekisteri::Application.routes.draw do
  resources :courses

  resources :paths

  resources :groups do
    match :path, :via => [:get], :on => :member
    match :touch, :via => [:get], :on => :collection
  end

  resources :posts

  resources :statistics do
    match :touch, :via => [:post], :on => :member
    match :show_month_after, :via => [:get], :on => :member
  end

  resources :students

  resources :entries

  root :to => 'groups#index'

  match 'api/student/:id'              => 'api#student'
  match 'api/groups'                   => 'api#groups'
  match 'api/groups/:id'               => 'api#group'
  match 'api/groups/:id/:year/:sorted' => 'api#group_year'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Opintorekisteri" %></title>
    <%= csrf_meta_tags %>
    <%= yield :head %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>
    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "entries", entries_path  %></li>
              <li><%= link_to "students", students_path %></li>
              <li><%= link_to "statistics", groups_path  %></li>
              <li><%= link_to "paths", paths_path  %></li>
              <li><%= link_to "courses", courses_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <div class="content">
                <%= yield %>
            </div>
          </div>

        </div><!--/row-->

      <footer>
        <p>&copy; RAGE 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>